#pragma once

//From glfw3.h

#define SOL_GAMEPAD_BUTTON_A               0
#define SOL_GAMEPAD_BUTTON_B               1
#define SOL_GAMEPAD_BUTTON_X               2
#define SOL_GAMEPAD_BUTTON_Y               3
#define SOL_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define SOL_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define SOL_GAMEPAD_BUTTON_BACK            6
#define SOL_GAMEPAD_BUTTON_START           7
#define SOL_GAMEPAD_BUTTON_GUIDE           8
#define SOL_GAMEPAD_BUTTON_LEFT_THUMB      9
#define SOL_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define SOL_GAMEPAD_BUTTON_DPAD_UP         11
#define SOL_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define SOL_GAMEPAD_BUTTON_DPAD_DOWN       13
#define SOL_GAMEPAD_BUTTON_DPAD_LEFT       14
#define SOL_GAMEPAD_BUTTON_LAST            SOL_GAMEPAD_BUTTON_DPAD_LEFT

#define SOL_GAMEPAD_BUTTON_CROSS       SOL_GAMEPAD_BUTTON_A
#define SOL_GAMEPAD_BUTTON_CIRCLE      SOL_GAMEPAD_BUTTON_B
#define SOL_GAMEPAD_BUTTON_SQUARE      SOL_GAMEPAD_BUTTON_X
#define SOL_GAMEPAD_BUTTON_TRIANGLE    SOL_GAMEPAD_BUTTON_Y

#define SOL_GAMEPAD_AXIS_LEFT_X        0
#define SOL_GAMEPAD_AXIS_LEFT_Y        1
#define SOL_GAMEPAD_AXIS_RIGHT_X       2
#define SOL_GAMEPAD_AXIS_RIGHT_Y       3
#define SOL_GAMEPAD_AXIS_LEFT_TRIGGER  4
#define SOL_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define SOL_GAMEPAD_AXIS_LAST          SOL_GAMEPAD_AXIS_RIGHT_TRIGGER